

################################################################
## Packages / Philips Hue Motion
################################################################

################################################################
## Add the following to your secrets.yaml file:
##
##   hue_url_guest_bathroom_lux: 'http://YOUR_HUE_BRIDGE_IP/api/YOUR_HUE_USERNAME/sensors/LUX_SENSOR_ID'
##   hue_url_guest_bathroom_motion: 'http://YOUR_HUE_BRIDGE_IP/api/YOUR_HUE_USERNAME/sensors/MOTION_SENSOR_ID'
##   hue_url_guest_bathroom_temperature: 'http://YOUR_HUE_BRIDGE_IP/api/YOUR_HUE_USERNAME/sensors/TEMPERATURE_SENSOR_ID'
##
## To find the SENSOR_ID for each sensor, open this URL in your
## browser:
##
##  http://192.168.1.110/api/uLim58d7aKOQeySb2UZAzP8-Qh-9UWWLMS-33P4b/sensors
##
##   hue_url_kitchen_motion: 'http://192.168.1.110/api/uLim58d7aKOQeySb2UZAzP8-Qh-9UWWLMS-33P4b/sensors/8'
##   hue_url_kidshall_motion: 'http://192.168.1.110/api/uLim58d7aKOQeySb2UZAzP8-Qh-9UWWLMS-33P4b/sensors/30'
##   hue_url_front_motion: 'http://192.168.1.110/api/uLim58d7aKOQeySb2UZAzP8-Qh-9UWWLMS-33P4b/sensors/34'
##
## Be sure to replace "YOUR_HUE_BRIDGE_IP" with the IP address
## of your Philips Hue bridge, and replace "YOUR_HUE_USERNAME"
## with the username for your Philips Hue bridge. Both of these
## items can be found in the phue.conf file in your config dir.
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.kidshall_motion:
      friendly_name: "Kids hall Motion"
      device_class: motion
    binary_sensor.kitchenhue_motion:
      friendly_name: "Kitchen"
      device_class: motion
    binary_sensor.frontroom_motion:
      friendly_name: "Front Room Motion"
      device_class: motion

    ################################################
    ## Sensor
    ################################################

    sensor.guest_bathroom_lux:
      friendly_name: "Guest Bathroom Lux"

    sensor.guest_bathroom_temperature:
      friendly_name: "Guest Bathroom Temperature"

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: rest
    name: frontroom_motion
    resource: !secret hue_url_front_motion
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
  - platform: rest
    name: kitchenhue_motion
    resource: !secret hue_url_kitchen_motion
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
  - platform: rest
    name: kidshall_motion
    resource: !secret hue_url_kidshall_motion
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2

################################################
## Sensor
################################################

sensor:
  - platform: rest
    name: guest_bathroom_lux
    resource: !secret hue_url_guest_bathroom_lux
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    scan_interval: 10

  - platform: rest
    name: guest_bathroom_temperature
    resource: !secret hue_url_guest_bathroom_temperature
    value_template: '{{ value_json.state.temperature|float / 100 }}'
    unit_of_measurement: '°C'
    scan_interval: 60