#####################################
#Configuration information for the  #
#telegram bot used for notifications#
#####################################

- platform: polling
  api_key: !secret telegram_bot_api_key_josh
  parse_mode: html
  allowed_chat_ids:
    - !secret telegram_bot_chat_id_josh

#- platform: polling
#  api_key: !secret telegram_bot_api_key_leigh
#  parse_mode: html
#  allowed_chat_ids:
#    - !secret telegram_bot_chat_id_leigh

#- platform: webhooks
#  api_key: !secret telegram_bot_api_key
#  parse_mode: html
#  allowed_chat_ids:
#    - !secret telegram_bot_chat_id